### ISSUE TITLE
Suddenly getting "Error: invalid_grant" when trying to get token

### ISSUE THREAD

**Issue by jascination** [andris9/xoauth2#10]
This was working 100% fine for several months, until I tried it today (first time I've tried authenticating in a week or so. My code is simple:

`````
xoauth2gen.getToken(function(err, token){
      if(err){
          return console.log("XOAUTH2 Error: " + err);
      }
      console.log("AUTH XOAUTH2 " + token);
      if(type === "full"){
        cb(token);
      }
  });
`````

Things I can verify: 

- I'm on the latest version of xoauth2@1.1.0, 
- The Refresh token I'm using is coming directly from a Google authentication I've just done (offline is enabled, as is force approvalprompt)
- The secret + clientID are correct and the same ones that granted the original refreshtoken

Any ideas what's up here?

**Comment by vu0tran** [comment]
+1. It seems to be only affecting some accounts, so I'm not exactly sure what's going on.

**Comment by jascination** [comment]
@vu0tran I fixed this a while ago but annoyingly forgot what the issue was.

I'm 80% sure what I had to do was go into the connected app permissions of the Gmail account that was connected, and de-register my app. The issue was that the permissions that were granted to my app were different from the permissions embedded in the refresh token.

**Comment by vu0tran** [comment]
Thanks for the follow up. We tried a couple more things including explicitly requesting offline access in our tokens on our iOS app. We'll see if that helps! Thanks!
