### ISSUE TITLE
Authentication fails for microsoft account

### ISSUE THREAD

**Issue by azamsolix** [andris9/xoauth2#17]
Hi,
I am trying to get token so i can pass it to imap .Below is the sample code .However,I am getting accessToken and i am passing it to imap and it is returning authentication failed.
  try {
//here i am getting access token and refreshtoken and 
      const accessToken = await client.getToken(tokenParams);
      var xoauth2 = require("xoauth2"), xoauth2gen;
      console.log('accesstoken', accessToken, accessToken.token.access_token);
       xoauth2gen = xoauth2.createXOAuth2Generator({
        user: "sathyakrishna2021@hotmail.com",
        clientId: "282abac0-3xxxxx9",
           clientSecret: "11w7Q~58UxxxxxxxxxxxxxxxxWBkWb.mPJOM1rgnI1a",
           accessUrl :'https://login.live.com/oauth20_token.srf',
        accessToken:accessToken.token.access_token,
        customPayload: {
            "access_type": "offline"
        }
    });

    // SMTP/IMAP
    xoauth2gen.getToken(function (err, token) {
        if (err) {
            return console.log(err);
        }
// Here i am getting token and i am passing this token to imap and it is returning authentication fail error
        console.log("AUTH XOAUTH2 " + token);
        let Imap = require('imap');

             var imap = new Imap({
            xoauth2 :token,
        host: 'outlook.office365.com',
        port: 993,
        tls: true,
        authTimeout: 3000,
                 tlsOptions: { rejectUnauthorized: false },
    debug:console.log
});
imap.connect()
imap.once('ready', function() {
    console.log('connectied')
      imap.end();
});
        imap.once('end', function() {
            console.log('Connection ended');
});
    });
    
     

    //   res.status(200).json({response:accessToken})
  } catch (error) {
    console.log('Access Token Error', error);
  }
am i doing something wrong?
Could you please help me with this?
Waiting for your response.
Thanks 
Azam Ahmed

**Comment by andris9** [comment]
This library has been unmaintained for the last 7 years. Both Google and Microsoft have their own OAuth authentication libraries now, so there is no need for the xoauth2 library. When you create an application in Azure Directory then there is an option to download a sample Node.js application that shows you how to use their library. You could also check how other applications handle OAuth2 with Microsoft, eg you can find a tutorial for using it with EmailEngine [here](https://docs.emailengine.app/setting-up-oauth2-with-outlook/)

**Comment by giacomobartoli** [comment]
@andris9 so there's no way to use node-imap library with the new Microsoft OAuth authentication?
My idea is to use their SDK to generate the token, then create the xoauth2 string and still use node-imap to get notified about new incoming emails.

**Comment by andris9** [comment]
@giacomobartoli I know nothing about the node-imap library. The only option I provide support for is  https://emailengine.app/ - you can use it to listen for incoming emails with Microsoft accounts as well.
