### ISSUE TITLE
Getting error as invalid_client from getToken method in case of Hotmail account

### ISSUE THREAD

**Issue by ScorpioKing** [andris9/xoauth2#7]
I am using,

```
xoauth2gen = xoauth2.createXOAuth2Generator({
    user: userId@hotmail.com
    clientId: Id,
    clientSecret: secret,
    refreshToken: refresh_token
});
xoauth2gen.getToken(function(err, token){});
```

While getToken throwing error as invalid_client.

**Comment by andris9** [comment]
You should also include correct `accessUrl` property. The default points to google which knows nothing about hotmail users.

**Comment by ScorpioKing** [comment]
Thank you!!

**Comment by azamsolix** [comment]
@ScorpioKing , could you please help me with the sample program on how you are getting token for hotmail accounts.i.e what properties you are passing in accessURL parameter ,custom headers and custom params?
Thanks
azam ahmed
