### ISSUE TITLE
Where to get my '{Client ID}' and '{Client Secret}' ?

### ISSUE THREAD

**Issue by Ulawun** [andris9/xoauth2#9]
Hello Andris,
Where do I get my '{Client ID}' and '{Client Secret}' please ?
I'm wondering why Thunderbird is working.
For setting up my SMTP mail sending
it doesn't need any '{Client ID}' or '{Client Secret}'.
Do you have any idea, where Thunderbird gets the '{Client ID}' and '{Client Secret}' from ?
Thanks a lot.

**Comment by andris9** [comment]
All the required information about using OAuth2 with Google can be found here (most other SMTP providers do not support OAuth): https://developers.google.com/identity/protocols/OAuth2
